# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OktoIDE' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OktoIDE
  pod 'Prestyler'
  pod 'SnapKit'
  pod 'ReachabilitySwift'
  pod 'KeychainSwift'
  pod 'SwipeCellKit'
  pod 'StatusAlert' 
  pod "ViewAnimator"

  target 'OktoIDETests' do
    inherit! :search_paths
    # Pods for testing
  end

end
